pool:
  name: "Azure Pipelines"
  VmImage: Ubuntu-18.04

resources:
  repositories:
    - repository: templates
      name: training-quind/training-esteban-template
      type: git

variables:
  - template: variables/vars-azure-pipeline.yml

extends:
  template: main.yml@templates
  parameters:
    language: react
